version: 2

updates:
  - package-ecosystem: npm
    directory: '/backend/javascript'
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: '/backend/typescript'
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: composer
    directory: '/backend/php/laravel'
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: cargo
    directory: '/backend/rust/balancer'
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: '/frontend/archifront'
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
