[package]
name = "balancer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
log = "0.4"
console_log = { version = "0.2", optional = true }

[features]
default = ["console_log"]