name: Archivel Quality

on:
  pull_request:

defaults:
  run:
    working-directory: ./backend/php/laravel

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-sysem: [ubuntu-latest]
        php-versions: ["8.0"]
        dependency-stability: [prefer-stable]

    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system}}

    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Install PHP Versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions}}

      - name: Copy .env.testing
        run: php -r "file_exists('.env.testing') || copy('.env.testing.example', '.env.testing');"

      - name: Install Dependencies
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Dump auto load
        run: composer dump-autoload

      - name: Run Lint
        run: composer lint

      - name: Run Formatter
        run: composer format
