name: docker-compose-build-up-archivel

on:
  push:
    branches:
      - main
      - canary
  pull_request:
    branches:
      - main
      - canary

jobs:
  build-up:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building Database MySQL
        run: docker-compose build architect_mysql

      - name: Build RabbitMQ
        run: docker-compose build architect_rabbitmq

      - name: Building Archivel
        run: docker-compose up -d archivel_1 archivel_2

      - name: Run composer
        run: docker exec -t archivel_1 composer install

      - name: Application Key
        run: docker exec -t archivel_1 php artisan key:generate

      - name: Run migrations
        run: docker exec -t archivel_1 php artisan optimize

      - name: Run migrations
        run: docker exec -t archivel_1 php artisan migrate

      - name: Building Archivel Nginx
        run: docker-compose build archivel_nginx

      - name: Running services Archivel Nginx
        run: docker-compose up -d archivel_nginx

      # - name: Testing Archifront
      #   run: docker run --rm --platform linux/x86_64 --network architect_architect_network appropriate/curl -fsSL http://archifront_nginx/

      - name: Testing Archivel
        run: docker run --rm --platform linux/x86_64 --network architect_architect_network appropriate/curl -fsSL http://archivel_nginx/

      # - name: Testing Balancer
      #   run: docker run --rm --platform linux/x86_64 --network architect_architect_network appropriate/curl -fsSL http://localhost:8080/

      - name: Stop containers
        if: always()
        run: docker-compose stop
