name: docker-compose-build-up

on:
  push:
    branches:
      - main
      - canary
  pull_request:
    branches:
      - main
      - canary

jobs:
  build-up:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d --build

      - name: Testing Archifront
        run: docker run --rm --platform linux/x86_64 --network architect_architect_network appropriate/curl -fsSL http://127.0.0.1/

      - name: Testing Archivel
        run: docker run --rm --platform linux/x86_64 --network architect_architect_network appropriate/curl -fsSL http://127.0.0.1:8000/

      - name: Testing Balancer
        run: docker run --rm --platform linux/x86_64 --network architect_architect_network appropriate/curl -fsSL http://127.0.0.1:8080/

      - name: Stop containers
        if: always()
        run: docker-compose stop
